version: '3.8'

networks:
  pcs-network:
    driver: bridge

services:
  pcs-front:
    build:
      context: ./pcs-front/
      dockerfile: Dockerfile
    container_name: pcs-front
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080/api
      NEXT_PUBLIC_ICON_URL: https://i.imgur.com/Yvs6KgF.png
      NEXT_PUBLIC_BIG_ICON_URL: https://i.imgur.com/AIEl1hF.png
    depends_on:
      - pcs-bdd
    networks:
      - pcs-network

  pcs-api:
    build:
      context: ./PCS-API/
      dockerfile: Dockerfile
    container_name: pcs-api
    environment:
      #DATABASE (Utilisation de postgres)
      DB_HOST: 77.237.246.8
      DB_NAME: pcs
      DB_USER: pcs-user
      DB_PASSWORD: GjE7tS5wa5C73f
      DB_PORT: 5432
      DB_SSLMODE: disable
      DB_TIMEZONE: Europe/Paris

      PORT_APP: 8080

      #TOKEN

      TOKEN_KEY: MKusxLaD3mzKKHWqJLtqTo85gBCgXRTa
      #Nombre d'expiration d'un token après sa génération
      TOKEN_EXPIRATION: 8760

      # STRIPE

      STRIPE_KEY: sk_test_51PNwOpRrur5y60cs5Yv2aKu9v6SrJHigo2cLgmxevvozEfzSDWFnaQhMwVH02RLc8R2xHdjkJ6QagZ7KDyYTVxZt00gadizteA
    ports:
      - "8080:8080"
    depends_on:
      - pcs-bdd
    networks:
      - pcs-network

  pcs-bdd:
    build:
      context: ./pcs-bdd/
      dockerfile: Dockerfile
    container_name: pcs-bdd
    environment:
      POSTGRES_DB: pcs
      POSTGRES_USER: pcs-user
      POSTGRES_PASSWORD: GjE7tS5wa5C73f
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pcs-network

volumes:
  postgres_data:
